### ISSUE TITLE
Script does not run due to TypeError

### ISSUE THREAD

**Issue by evanmiltenburg** [ramakrishnavedantam928/pyCider#3]
Running the standard notebook with the `df`-argument set to `"coco-val-df"`, I get this error:

```
Traceback (most recent call last):
  File "cidereval.py", line 41, in <module>
    scores = scorer.evaluate()
  File "/Users/Emiel/PhD/Repositories/cider/pyciderevalcap/eval.py", line 37, in evaluate
    score, scores = scorer.compute_score(self.gts, self.res)
  File "/Users/Emiel/PhD/Repositories/cider/pyciderevalcap/cider/cider.py", line 55, in compute_score
    (score, scores) = cider_scorer.compute_score(self._df)
  File "/Users/Emiel/PhD/Repositories/cider/pyciderevalcap/cider/cider_scorer.py", line 196, in compute_score
    score = self.compute_cider(df_mode)
  File "/Users/Emiel/PhD/Repositories/cider/pyciderevalcap/cider/cider_scorer.py", line 170, in compute_cider
    vec, norm, length = counts2vec(test)
  File "/Users/Emiel/PhD/Repositories/cider/pyciderevalcap/cider/cider_scorer.py", line 125, in counts2vec
    vec[n][ngram] = float(term_freq)*(self.ref_len - df)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by ramavedantam** [comment]
Hi!

The issue was an inconsistency which crept in at some point (code expected 'coco-val' while the parameter being provided was 'coco-val-df'). Should be fixed now.
